/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_epicvon2468_cinterop_jni_JNIImpls */

#ifndef _Included_io_github_epicvon2468_cinterop_jni_JNIImpls
#define _Included_io_github_epicvon2468_cinterop_jni_JNIImpls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_epicvon2468_cinterop_jni_JNIImpls
 * Method:    getNativeNullPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_epicvon2468_cinterop_jni_JNIImpls_getNativeNullPointer(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif